const $=id=>document.getElementById(id);
const INCOME_STEPS=[{label:'1 LPA+',factor:1},{label:'2 LPA+',factor:.94},{label:'3 LPA+',factor:.88},{label:'5 LPA+',factor:.78},{label:'10 LPA+',factor:.62},{label:'15 LPA+',factor:.50},{label:'25 LPA+',factor:.35},{label:'50 LPA+',factor:.20},{label:'1 Cr+',factor:.12},{label:'10 Cr+',factor:.025},{label:'25 Cr+',factor:.01},{label:'50 Cr+',factor:.004},{label:'75 Cr+',factor:.002},{label:'1 B+',factor:.001},{label:'10 B+',factor:.00015},{label:'50 B+',factor:.00003},{label:'1 Trillion+',factor:.000001},{label:'∞',factor:1}];
const CAT=[{m:.0001,r:10,l:'Single Origin Mythic Blend',d:'Statistically extreme scarcity.'},{m:.001,r:9,l:"Collector's Edition",d:'Exceptionally rare profile.'},{m:.005,r:8,l:'Rare Reserve',d:'Very limited statistical pool.'},{m:.01,r:7,l:'Small Batch Import',d:'Uncommon profile.'},{m:.02,r:6,l:'Limited Batch',d:'Small statistical pool.'},{m:.05,r:5,l:'Specialty Store',d:'Noticeably selective.'},{m:.1,r:4,l:'Premium Aisle',d:'Above-average selectivity.'},{m:.2,r:3,l:'Decent Brand',d:'Moderately common.'},{m:.5,r:2,l:'Standard Shelf Stock',d:'Relatively common.'},{m:1,r:1,l:'Bulk Bin Basics',d:'Broadly available statistically.'}];
function ft(cm){let t=cm/2.54,f=Math.floor(t/12),i=Math.round(t-f*12);if(i===12){f++;i=0}return `${f}'${i}"`}
function rangeUI(t){let a=$(t+'Min'),b=$(t+'Max'),lo=+a.value,hi=+b.value;if(lo>hi){if(document.activeElement===a)b.value=lo;else a.value=hi;lo=+a.value;hi=+b.value}$(t+'MinOut').textContent=t==='age'?lo:`${lo} cm (${ft(lo)})`;$(t+'MaxOut').textContent=t==='age'?(hi>=70?'70+':hi):`${hi} cm (${ft(hi)})`;let p=(lo-+a.min)/(+a.max-+a.min)*100,q=(hi-+a.min)/(+a.max-+a.min)*100;$(t+'Range').style.setProperty('--start',p+'%');$(t+'Range').style.setProperty('--end',q+'%')}
function incomeUI(){let i=+$('income').value;$('incomeOut').textContent=INCOME_STEPS[i].label;$('income').style.setProperty('--income-pos',i/17*100+'%');$('incomeTicks').innerHTML=INCOME_STEPS.map((x,n)=>`<button type="button" class="income-tick ${n===i?'active':''}" data-i="${n}">${x.label}</button>`).join('');document.querySelectorAll('.income-tick').forEach(b=>b.onclick=()=>{$('income').value=b.dataset.i;incomeUI()})}
function orF(n){let v=[...document.querySelectorAll(`input[name="${n}"]:checked`)].map(x=>+x.value);return v.length?Math.min(1,v.reduce((a,b)=>a+b,0)):0}
function andF(n){let v=[...document.querySelectorAll(`input[name="${n}"]:checked`)].map(x=>+x.value);return v.length?v.reduce((a,b)=>a*b,1):1}
function agePool(a,z){return DATA.ageBands.reduce((s,b)=>{let lo=Math.max(a,b.min),hi=Math.min(z,b.max===70?70:b.max);return hi>=lo?s+b.male:s},0)}
function heightF(a,z){let hs=DATA.heights.filter(h=>h>=a&&h<=z);if(!hs.length)return 0;let lo=Math.min(...hs),hi=Math.max(...hs);return Math.max(.00001,(DATA.heightModel[lo]||0)-(DATA.heightModel[hi+5]||0))}
function renderCat(p){let t=CAT.find(x=>p<=x.m)||CAT[CAT.length-1],c='';for(let i=0;i<10;i++)c+=`<span class="can ${i<t.r?'':'empty'}">🥫</span>`;return `<div class="rhint">🥫 More cans = scarcer man · Fewer cans = more common</div><div class="rcans">${c}</div><div class="rscore">${t.r} / 10</div><div class="rlbl">${t.l}</div><div class="rdesc">${t.d}</div>`}
function calc(){try{let a=+$('ageMin').value,z=+$('ageMax').value,h1=+$('heightMin').value,h2=+$('heightMax').value;if(a>z||h1>h2)throw Error('Check the selected range.');let af=agePool(a,z)/agePool(21,70),hf=heightF(h1,h2),ef=+$('education').value,ii=+$('income').value,inf=INCOME_STEPS[ii].factor,wf=orF('emp'),rf=orF('rel'),bf=orF('body'),mf=orF('mar'),lf=orF('loc'),ff=andF('finance'),as=andF('asset'),life=andF('life');if(!wf||!rf||!bf||!mf||!lf)throw Error('Select at least one option in each required section.');if($('exclude-obese').checked)bf*=.77;let factor=af*hf*ef*inf*wf*rf*bf*mf*lf*ff*as*life,base=agePool(a,z),count=Math.round(base*factor),pct=factor*100;$('count').textContent=count<1?'≈ 0':`≈ ${count.toLocaleString('en-IN')}`;$('percent').textContent=(pct<.01?pct.toFixed(4):pct<.1?pct.toFixed(3):pct<1?pct.toFixed(2):pct.toFixed(1))+'%';$('confidence').textContent=lf<1||ii>=8?'MODELLED COVERAGE':'DEMOGRAPHIC ESTIMATE';$('resultText').textContent=count<1?'The selected combination produces less than one modelled match in the chosen demographic base.':`The model estimates roughly ${count.toLocaleString('en-IN')} men in the selected demographic base. This is not a live availability count.`;$('meterBar').style.width=Math.min(100,Math.max(.25,pct))+'%';$('rating-display').innerHTML=renderCat(factor);$('tags').innerHTML=[`Age ${a}–${z>=70?'70+':z}`,`Height ${h1}–${h2} cm`,`Education ${$('education').selectedOptions[0].text}`,`Income ${INCOME_STEPS[ii].label}`,$('exclude-obese').checked?'Non-Obese Only':'Body filter',...[...document.querySelectorAll('input[name="mar"]:checked')].map(x=>x.parentElement.textContent.trim()),...[...document.querySelectorAll('input[name="loc"]:checked')].map(x=>x.parentElement.textContent.trim())].map(x=>`<span>${x}</span>`).join('');let rows=[['Age pool',af],['Height',hf],['Education',ef],['Income',inf],['Employment',wf],['Financial profile',ff],['Religion',rf],['Body composition',bf],['Assets',as],['Lifestyle',life],['Marital status',mf],['Location / nationality',lf]];$('breakdown').innerHTML='<h3>Model breakdown</h3>'+rows.map(r=>`<div class="break-row"><span>${r[0]}</span><b>${(r[1]*100).toFixed(r[1]*100<1?3:1)}%</b></div>`).join('')}catch(e){flash(e.message)}}
function resetCalc(){document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);[['mar','0.52'],['loc','1'],['emp','0.28'],['rel','1'],['body','0.40'],['finance','1']].forEach(([n,v])=>{let x=document.querySelector(`input[name="${n}"][value="${v}"]`);if(x)x.checked=true});$('education').selectedIndex=0;$('ageMin').value=25;$('ageMax').value=34;$('heightMin').value=150;$('heightMax').value=195;$('income').value=0;rangeUI('age');rangeUI('height');incomeUI();$('count').textContent='—';$('percent').textContent='—';$('confidence').textContent='WAITING';$('resultText').textContent='Set your standards and build your King profile.';$('meterBar').style.width='0';$('rating-display').innerHTML='<div class="rplaceholder">Awaiting calibration…</div>';$('tags').innerHTML='';$('breakdown').innerHTML=''}
function flash(t){let x=document.querySelector('.toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2600)}
async function share(){let t=`IN Female Delusion Calculator by @themachopodml\nKing pool: ${$('count').textContent} (${ $('percent').textContent })`;try{if(navigator.share)await navigator.share({title:'IN Female Delusion Calculator',text:t,url:location.href});else{await navigator.clipboard.writeText(t+'\n'+location.href);flash('Result copied.')}}catch(e){if(e.name!=='AbortError')flash('Share failed.')}}
(function(){let c=$('stars'),x=c.getContext('2d'),w,h,s=[];function size(){w=c.width=innerWidth;h=c.height=innerHeight;s=Array.from({length:150},()=>({x:Math.random()*w,y:Math.random()*h,r:.2+Math.random()*1.1,p:Math.random()*6.28}))}function draw(t){x.clearRect(0,0,w,h);s.forEach(a=>{x.globalAlpha=.12+.18*Math.sin(t*.001+a.p);x.fillStyle='#ffc94a';x.beginPath();x.arc(a.x,a.y,a.r,0,6.28);x.fill()});requestAnimationFrame(draw)}addEventListener('resize',size);size();requestAnimationFrame(draw)})();
document.addEventListener('DOMContentLoaded',()=>{rangeUI('age');rangeUI('height');[$('ageMin'),$('ageMax')].forEach(x=>x.oninput=()=>rangeUI('age'));[$('heightMin'),$('heightMax')].forEach(x=>x.oninput=()=>rangeUI('height'));incomeUI();$('income').oninput=incomeUI;$('calculateBtn').onclick=calc;$('resetBtn').onclick=resetCalc;$('shareBtn').onclick=share});